language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
      dist: xenial
      sudo: true

# commands to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - flake8 .
  - mypy --ignore-missing-imports .
