stages:
  - test
  - name: publish
    if: branch = master AND type = push
  - name: deploy
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      name: Python 3.7
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-e.txt
      script:
        - flake8 .
        - mypy --ignore-missing-imports .
      language: python
      python: 3.7
      dist: xenial
      sudo: true
    - stage: test
      name: Python 3.6
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-e.txt
      script:
        - flake8 .
        - mypy --ignore-missing-imports .
      language: python
      python: 3.6
      dist: xenial
      sudo: true
    - stage: publish
      script:
        - echo $GCP_SERVICE_ACCOUNT | base64 --decode > keyfile.json
        - cat keyfile.json | docker login -u _json_key --password-stdin https://gcr.io
        - docker build -t gcr.io/$GCP_PROJECT_ID/apophis:$TRAVIS_COMMIT .
        - docker tag gcr.io/$GCP_PROJECT_ID/apophis:$TRAVIS_COMMIT gcr.io/$GCP_PROJECT_ID/apophis:latest
        - docker push gcr.io/$GCP_PROJECT_ID/apophis:$TRAVIS_COMMIT
        - docker push gcr.io/$GCP_PROJECT_ID/apophis:latest
      services:
        - docker
    - stage: deploy
      install:
        - sudo apt-get install -y apt-transport-https
        - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        - sudo apt-get update
        - sudo apt-get install -y kubectl
      script:
        - ./deploy.sh
