stages:
  - test
  - name: publish
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      name: Python 3.7
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-e.txt
      script:
        - flake8 .
        - mypy --ignore-missing-imports .
      language: python
      python: 3.7
      dist: xenial
      sudo: true
    - stage: test
      name: Python 3.6
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-e.txt
      script:
        - flake8 .
        - mypy --ignore-missing-imports .
      language: python
      python: 3.6
      dist: xenial
      sudo: true
    - stage: publish
      script:
        - echo $SERVICE_ACCOUNT | base64 -D > keyfile.json
        - cat keyfile.json | docker login -u _json_key --password-stdin https://gcr.io
        - echo publishing image
      services:
        - docker
    - stage: deploy
      script:
        - echo deploy
