language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true


# commands to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-e.txt

# command to run tests
script:
  - flake8 .
  - mypy --ignore-missing-imports .
