language: python

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      name: Python 3.7
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-e.txt
      script:
        - flake8 .
        - mypy --ignore-missing-imports .
      python: 3.7
      dist: xenial
      sudo: true
    - stage: test
      name: Python 3.6
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-e.txt
      script:
        - flake8 .
        - mypy --ignore-missing-imports .
      python: 3.6
      dist: xenial
      sudo: true
    - stage: deploy
      script:
        - echo deploy
