version: '3'
services:
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_DB: apophis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./run/pg:/var/lib/postgresql/data
  apophis:
    image: packetfire/apophis
    build:
      context: ./
    volumes:
      - ./run/music:/var/lib/apophis/music
    environment:
      MUSIC_DATA_DIR: /var/lib/apophis/music